name: Run Seeds on Render

# 手動実行できるようにするトリガー
on:
  workflow_dispatch:

jobs:
  run-seeds:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy (this will run seeds)
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys